backend:
  name: github
  repo: softshiraz/web
  branch: main
  # آدرس Worker شما (دقیقاً همین رو نگه دار)
  base_url: https://admin.softshiraz.workers.dev

media_folder: "cards/images"
public_folder: "/cards/images"

collections:
  - name: "movies"
    label: "اکران‌های آینده"
    folder: "cards"
    create: true
    delete: false
    format: "frontmatter"
    extension: "md"
    fields:
      - {label: "تاریخ و زمان", name: "datetime", widget: "datetime", required: true, date_format: "YYYY/MM/DD", time_format: "HH:mm"}
      - {label: "نام فیلم", name: "title", widget: "string", required: true}
      - {label: "پوستر فیلم", name: "poster", widget: "image", required: true}
      - {label: "تخفیف ویژه", name: "has_discount", widget: "boolean", default: false}
      - {label: "توضیحات", name: "body", widget: "markdown"}
