backend:
  name: github
  repo: softshiraz/web
  branch: main
  auth_endpoint: https://github.com/login/oauth/authorize
  token_endpoint: https://github.com/login/oauth/access_token
  client_id: Iv23lii1aTw39LkVrh1h
  client_secret: 73be1bd6dc67c9435dedc0a59f48a54f924a7abe

media_folder: "cards/images"
public_folder: "/cards/images"

collections:
  - name: "movies"
    label: "اکران‌های آینده"
    folder: "cards"
    create: true
    delete: false
    slug: "{{datetime}}-{{title}}"
    format: "frontmatter"
    extension: "md"
    fields:
      - {label: "تاریخ و زمان", name: "datetime", widget: "datetime", required: true, date_format: "YYYY/MM/DD", time_format: "HH:mm"}
      - {label: "نام فیلم", name: "title", widget: "string", required: true}
      - {label: "پوستر فیلم", name: "poster", widget: "image", required: true}
      - {label: "تخفیف ویژه", name: "has_discount", widget: "boolean", default: false}
      - {label: "توضیحات", name: "body", widget: "markdown"}
